### ISSUE TITLE
Render public transport platforms

### ISSUE THREAD

**Issue by riQQ** [ENT8R/streetcomplete-mapstyle#105]
This makes orientation on train and tram stations easier.

Tagging: `public_transport=platform`

**Comment by westnordost** [comment]
Not possible

**Comment by riQQ** [comment]
So it's blocked by jawg?

**Comment by westnordost** [comment]
yes

**Comment by riQQ** [comment]
@Joxit any chance to add public transport platforms to Jawg?

**Comment by Joxit** [comment]
Hello @riQQ, I'm sorry this will not be possible, supporting public platforms and stations is not an easy task.

At @jawg we work with the French national railway company (SNCF) where we are supporting indoor mapping for stations with platforms etc. You can see our work [here](https://www.transilien.com/fr/gare/paris-gare-du-nord-8727103) (at the end of the page you can slide up the map).

We do not want to bring this kind of work in our all purpose tileset, at least not for the next few years, because that's not in the use cases we want to cover (which is a simple, beautiful and easy to use map).

**Comment by riQQ** [comment]
Thanks for the information. Having the outdoor public transport platforms in StreetComplete would be really good for orientation. All the further details wouldn't be necessary.

**Comment by westnordost** [comment]
StreetComplete is just one use case of rendering a map. A very specific one at that.
