### ISSUE TITLE
Town label blocked by village label

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#113]
I have not investigated it in more detail but often prominent place labels are blocked by minor ones without a clear reason for that.

https://www.openstreetmap.org/node/243643366 the most prominent in its area gets blocked by https://www.openstreetmap.org/node/31901459

It makes navigation across lower zoom levels harder, what is not typical/critical but sometimes useful (while prefetching data before trip or checking specific location for some reason)

**Comment by matkoniecz** [comment]
Interesting, I can reproduce it on phone but not on https://streetcomplete.github.io/streetcomplete-mapstyle/?provider=jawg&style=light

@Joxit Is it to be expected that both village and town https://www.openstreetmap.org/node/243643366 / https://www.openstreetmap.org/node/31901459 get `scalerank=7` ?

It seems to me that even small town should have different `scalerank`.

Though maybe sorting by `type=city/town/village/hamlet` would be beneficial as `scalerank` puts everything from towns to hamlets into `scalerank=7`.

**Comment by Joxit** [comment]
Hi there,

Yes this may happen. Scalerank are numbers from 0 to 7, so you can have villages and towns with a scalerank = 7.

IMO, this is a style/lib issue:
- via your style you can order your layers, put the styling of towns before villages, thanks to this your towns will appear before your villages
- we are sorting places before serving the tile. And we can notice that `Wolbrom` is before `Łobzów` inside the tile `12/2273/1382.pbf`. IIRC, map libraries draw the elements in the reverse order of the tiles so that in the case of collisions, the previous element is removed. Maybe there is a problem here with Tangram?

**Comment by matkoniecz** [comment]
That is weeeird. Changing https://github.com/streetcomplete/streetcomplete-mapstyle/blob/jawg/layers/labels.yaml#L76 to

`                    size: 39`

works fine both in app and in web preview.

Changing it to

`                    size: function() { return 39; }`

works fine in web version and is completely ignored in app.

**Comment by westnordost** [comment]
Try "39px"

Am 29. November 2021 23:29:49 MEZ schrieb Mateusz Konieczny ***@***.***>:
>That is weeeird. Changing
>https://github.com/streetcomplete/streetcomplete-mapstyle/blob/jawg/layers/labels.yaml#L76
>to
>
>`                    size: 39`
>
>works fine both in app and in web preview.
>
>Changing it to
>
>`                    size: function() { return 39; }`
>
>works fine in web version and is completely ignored in app.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/streetcomplete-mapstyle/issues/113#issuecomment-982082639

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
Thanks! That was *very* helpful
