### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [ENT8R/streetcomplete-mapstyle#146]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

Opened this because I only see tag usage by editor mentioned on Taginfo, not the map style.

**Comment by matkoniecz** [comment]
> tag usage by editor mentioned on Taginfo 

note that it is more than bit outdated, I may need to drop it if I will not find time to fix it

**Comment by westnordost** [comment]
This ticket doesn't make sense, because the mapstyle uses vector tiles with data already processed from OpenStreetMap. I.e. it does not use any openstreetmap tags directly. It would be jawg.io / mapbox / stadia maps / maptiler etc. where it would make sense to have them in taginfo projects, not map styles.

**Comment by danieldegroot2** [comment]
Sure. Maplibre/Mapbox I have opened an issue. Mapbox/Jawg/Stadiamaps/Maptiler/... some things I am not sure they are just forks of the other ones with little to no changes and no commits in the last 2-3 years. It gets confusing quite fast unfortunately.
