### ISSUE TITLE
display barriers

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#4]
For survey on foot displaying barrier=wall/fence/hedge/city_wall/retaining_wall would be useful

Partially blocked by https://github.com/tilezen/vector-datasource/issues/1403

**Comment by westnordost** [comment]
With the micro-mapping done with mapping all kinds of fences, also around private property, this can add all kinds of clutter to the map. I don't expect that users will stride far from the street and/or ways anyway because usually, there is also not that much to solve quest-wise.
So, I do not think it is worth adding that.

**Comment by matkoniecz** [comment]
Ok, I will close it - though in my case I at the same time used StreetComplete and attempted to map missing foorways - so fences aground private property blocking access were for me main reason for adding that.
