### ISSUE TITLE
Show crossings

### ISSUE THREAD

**Issue by rugk** [ENT8R/streetcomplete-mapstyle#47]
As StreetComplete is primarily an app for pedestrians (and there is even a crossing quest), I'd say it would be useful to see crossings. For zebra crossings just some black/white stuff e.g.

**Comment by ENT8R** [comment]
Hmm... I'm not sure if that would be possible at all, because crossings are very often only nodes and then you can't determine the direction of the crossing... So the zebra crossing would be e.g. shown in the direction of the cars and not the direction of the pedestrians...
Also tangram-es can't apply a dash-style to nodes but to ways...

**Comment by westnordost** [comment]
StreetComplete is not an orientation app. The surveyor will spot zebra crossing when he looks up from his smartphone.

The surveyor will also not just walk on the motorway just because the motorway is painted in the same style as roads.

**Comment by rugk** [comment]
Okay.
