### ISSUE TITLE
Problems with ł sign in name

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#69]
name "Bronowice Małe" at https://www.openstreetmap.org/?mlat=50.0849&mlon=19.8799#map=15/50.0849/19.8799 is displayed as "Bronowice Mae" ("ł" is missing).

Curiously in my map style it is displayed as "Bronowice Małe" ( https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/assets/map_theme/fork-style.yaml ) and in OSM it is mapped at https://www.openstreetmap.org/node/3009691224#map=16/50.0867/19.8803 so maybe not OSM is source of this data

**Comment by matkoniecz** [comment]
Form what I remember similar issues were caused by Mapzen using who on first data - but this time it is correct ( https://spelunker.whosonfirst.org/id/85897813/ )

Note that location of its node matches exactly label location, unlike OSM node.

**Comment by ENT8R** [comment]
This was also caused by whosonfirst.org, so this is covered by #14:

![bronowice_male](https://user-images.githubusercontent.com/25306497/63450713-df045700-c442-11e9-8bd0-490a9140bf10.png)

The reason why it is displayed as "Bronowice Małe" in your map style is because you prefer to use Polish labels with
```yaml
name_source: |
  function() {
    return feature['name:pl'] || feature.name;
  }
```
But I don't really know why it showed "Bronowice Mae" when you used this mapstyle, because this would mean that the `name:en` tag would be used. Did you spot the issue in the app or in the browser, or did you set your phone's language to English?

**Comment by matkoniecz** [comment]
> did you set your phone's language to English?

Yes, most of the time I have my phone in this language.

**Comment by matkoniecz** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/issues/1611 - supposed it is fixed already in original data source

Closing as fixed
