### ISSUE TITLE
used font has poor support for ę, ś, ą, ń, ł

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#75]
This letters appear to be smaller/slimmer than other.

https://www.openstreetmap.org/#map=19/50.07514/19.93227

![screen01](https://user-images.githubusercontent.com/899988/83347869-53501d00-a328-11ea-8775-825c2a6d2c9d.png)

**Comment by westnordost** [comment]
Probably the font used does actually not support these letters, so tangram-es is using some fallback.
We could use roboto for the font, the standard font on Android.

**Comment by ENT8R** [comment]
Actually, the font does support these characters, I somehow used the files that were hosted by Google (which strangely only seem to support a limited character set) instead of the original font files of the Github repo: https://github.com/JulietaUla/Montserrat/

This is the difference when replacing the files with the correct ones (done with https://github.com/ENT8R/streetcomplete-mapstyle/commit/3ca203bb865180ca669b6b95a7f78a0cdfdb57a7):

<img src="https://user-images.githubusercontent.com/25306497/83359225-44458b00-a379-11ea-8b0b-756bf4653928.png" width="320px"> <img src="https://user-images.githubusercontent.com/25306497/83359228-46a7e500-a379-11ea-9d36-d4a51b76ac44.png" width="320px">

**Comment by matkoniecz** [comment]
So it is fixed, right? Thanks!

**Comment by ENT8R** [comment]
I also currently noticed that the used font had a major update in late 2017 ([`v7.200`](https://github.com/JulietaUla/Montserrat/releases/tag/v7.200)) where the weight of the fonts were adjusted:
<p align="center"><img src="https://user-images.githubusercontent.com/2414972/32410047-f4ae44a4-c196-11e7-847d-79b3fbbc4769.png" height="300px"></p>

The current version of StreetComplete [still uses the old version v6.0](https://github.com/westnordost/StreetComplete/tree/master/app/src/main/assets/map_theme/fonts), so if the new font files will be used instead, there will be a noticeable change in the used font weight.
I don't know if this is acceptable @westnordost, or should we better switch to use `weight: 500` by default instead of `weight: 400` to prevent this visible change?

**Comment by westnordost** [comment]
Yes could be done like that. But using the Roboto font is perhaps the better choice overall, for visual consistency. Alternatively, mabye use the Montserrat font maybe everywhere in the app?

**Comment by ENT8R** [comment]
Well, this would be your decision :) I made some screenshots so you can decide what looks better:
Montserrat does somehow look a lot more heavier...
| Roboto | Montserrat |
| :-------------: |:-------------:|
| <img src="https://user-images.githubusercontent.com/25306497/83362956-ca6fca80-a395-11ea-991b-46493f49efe5.jpg" width="300px"> | <img src="https://user-images.githubusercontent.com/25306497/83362963-d065ab80-a395-11ea-8d59-6b1c9a65570a.jpg" width="300px"> |
| <img src="https://user-images.githubusercontent.com/25306497/83362954-c8a60700-a395-11ea-94b5-89e91f895d2a.jpg" width="300px"> | <img src="https://user-images.githubusercontent.com/25306497/83362959-cf347e80-a395-11ea-95dd-b84d06b67ca0.jpg" width="300px"> |
| <img src="https://user-images.githubusercontent.com/25306497/83362953-c774da00-a395-11ea-9e82-b05b955c56ce.jpg" width="300px"> | <img src="https://user-images.githubusercontent.com/25306497/83362958-cc398e00-a395-11ea-81a1-5f02a201ed72.jpg" width="300px"> |

**Comment by matkoniecz** [comment]
For me Robot seems clearly better.

**Comment by westnordost** [comment]
Yeah, I also think that Roboto is a better fit.

**Comment by rugk** [comment]
I like Montserrat quite much. Looks a little playful…

**Comment by matkoniecz** [comment]
> Looks a little playful…

I agree with it, but for me it is Comic Sans kind of playful - cringe/unwelcome/forced kind.
